name: Unit Tests

on: [pull_request]

jobs:
  build:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Jest Tests
        uses: stefanoeb/jest-action@1.0.4

      - name: Upload Test Report
        uses: actions/upload-artifact@v1.0.0
        with:
          name: unit-test-report
          path: ./test-report.html
