name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Cypress tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cypress Tests
        uses: cypress-io/github-action@v2.9.7
